CREATE SEQUENCE seq_archived_drinks START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_archived_desserts START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_employee_transfers START WITH 1 INCREMENT BY 1;